### ISSUE TITLE
Tree-shaking doesn't work

### ISSUE THREAD

**Issue by adi518** [mohsinulhaq/react-popper-tooltip#97] opened 2020-07-15 15:11 UTC
I'm building a component library that uses `TooltipTrigger` (version `2.11.1`). Unfortunately, it breaks tree-shaking by probably introducing some side-effects. I'm building with Rollup.

**Comment by mohsinulhaq** [comment] 2020-07-15 15:18
can you try with the latest version and let me know if it's still the case?

**Comment by adi518** [comment] 2020-07-15 15:36
I already tried, but I'll try again just to confirm.

**Comment by adi518** [comment] 2020-07-15 15:57
I upgraded to latest version and it still fails. See this gist for the code that fails tree-shaking: https://gist.github.com/adi518/f0f1bedb9b0124a06aca2954003620fd

**Comment by mohsinulhaq** [comment] 2020-07-15 16:12
I have a theory, maybe this line https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/package.json#L18 is causing rollup to think that the library has side-effects, even though I specify that only importing CSS will have a side-effect.

Ideally, it should have worked because rollup from our build system has marked the export as pure.

What you can do is use v3.0.0, where I had temporarily removed this CSS side-effect and let me know if that helps.

![image](https://user-images.githubusercontent.com/7688231/87568874-f516a800-c6e3-11ea-9190-fef8c2aa3b44.png)

**Comment by adi518** [comment] 2020-07-15 16:23
I reinstalled at fixed version `3.0.0` and looks like the result is the same: https://gist.github.com/adi518/d7c06eb088997b691d92273328ce05e8

**Comment by mohsinulhaq** [comment] 2020-07-15 16:43
maybe your project is using the commonjs version of the library, instead of the esm version.
can you create a sample project using `react-popper-tooltip` that uses rollup?

**Comment by adi518** [comment] 2020-07-15 17:33
I'm fairly sure Rollup picks the esm version, but I'll create a quick repro.

**Comment by adi518** [comment] 2020-07-18 23:07
Here's the reproduction: https://github.com/adi518/react-popper-tooltip-treeshake-reproduction

**Comment by adi518** [comment] 2020-07-20 22:45
@mohsinulhaq ?

**Comment by mohsinulhaq** [comment] 2020-07-21 20:10
@adi518 thanks for the detailed example, really sorry, I haven't had time to look into it. Will do as soon as I'm free.

**Comment by adi518** [comment] 2020-07-21 20:36
Thanks, I appreciate that.

**Comment by mohsinulhaq** [comment] 2020-07-21 21:38
https://github.com/adi518/react-popper-tooltip-treeshake-reproduction/pull/1/files
so the issue seems to be with the publish config of the ui-components library
you are not declaring external libraries to rollup, so rollup is bundling them into the main bundle, thus you lose on the tree-shake magic
you could either declare our lib as external, or use that generic function to mark all deps as external, so that they taken from the node_modules

try the build out with my changes and let me know

**Comment by adi518** [comment] 2020-07-21 23:26
It works, but I fail to understand why I'm losing the tree-shaking when I bundle it in. The library has many deps, not all of them are considered peer deps though.

**Comment by mohsinulhaq** [comment] 2020-07-22 22:49
I guess it's because ui-components is a library, not an application, libraries should always ship with its own code importing other code. Only applications need to bundle everything into one file. And they don't have the tree-shaking problem as they aren't going to be imported.

**Comment by adi518** [comment] 2020-07-23 18:01
It makes sense to have a React components library sets React as a peer dependency, but I'm not sure it makes sense to externalize *any* dependency. From my understanding of tree-shaking, the idea is to provide your code as an ESM build, which is then compatible with other ESM builds and can be tree-shake-compatible. I'm going to try and fork this repository and attempt to find the side-effect(s) that impairs its tree-shake.

**Comment by mohsinulhaq** [comment] 2020-07-23 18:32
i think there is a confusion between peer dependency and dependency

peer dependency means that the library user should provide it
and dependency means that on npm install, that package will install its own package
if you bundle a dependency in your own code, it's no longer a dependency

**Comment by adi518** [comment] 2020-07-24 11:56
There's no confusion. Some dependencies can be bundled in and that's fine. Also, if you think about it, any dependency that as an ESM bundle can be bundled in and. it wouldn't matter because it can be shaken off in the consumer bundle.

**Comment by mohsinulhaq** [comment] 2020-07-24 12:00
How do you decide which dependency to bundle and which one to not? Also, ESM and bundle have little overlap. I have seen then when you use ESM, you don't usually "bundle", and just let npm handle the dependencies via package.json and webpack/rollup handle tree-shaking via import/export.

**Comment by adi518** [comment] 2020-07-24 12:05
With common sense. If I create a React component library, the consumer have it. It's like buying an expansion product, it depends on having the main product for it to work. Same goes for this library, I expect Popper to be a peer dependency and not bundled in.

**Comment by mohsinulhaq** [comment] 2020-07-24 12:10
Here you are describing which module should be a peer-dep and which one should be a dependency. But my question was about your statement that "some dependencies can be bundled". So we are talking only about dependencies and not peer-dependencies. My question is, which dependency do you bundle in and which dependency do you leave out in package.json itself? Do you have any example where and ESM library bundles its dependency inside its `dist/index.js` instead of keeping it in package.json as a dependency?

**Comment by adi518** [comment] 2020-07-24 13:34
So I had a nice discussion with a colleague of mine about this and I finally hit the nail, realising my mistake. I totally understand why it should be externalised now and the exact difference to a peer dependency. Thanks for the great support. 👍

**Comment by adi518** [comment] 2020-07-24 21:48
So I externalized everything, my tree-shake check passes, but my app build still shows Popper, despite not using it. It's getting frustrating, haha.

**Comment by mohsinulhaq** [comment] 2020-07-25 09:48
https://github.com/adi518/react-popper-tooltip-treeshake-reproduction/pull/2/files
this seems to be happening with react-popper and/or @popperjs/core itself as well
you can raise this issue with them and get to the bottom of this
there is learning in this probably for both of us

**Comment by adi518** [comment] 2020-07-25 10:14
I did check what Popper say about TS at the outset of this, but failed to check the imports in this library. See: https://popper.js.org/docs/v2/tree-shaking/

It seems your code imports it the wrong way, which brings the entire Popper library:
- https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/TooltipTrigger.tsx#L6
- https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/types.ts

**Comment by mohsinulhaq** [comment] 2020-07-25 13:50
I only import types from "@popperjs/core" which is stripped away in the final dist build. Look at the content of the package tarball. It only has the `react-popper` import. But `react-popper` itself is importing `@popperjs/core` like this: https://github.com/popperjs/react-popper/blob/master/src/usePopper.js#L7

![image](https://user-images.githubusercontent.com/7688231/88458320-d4e8a500-ceaa-11ea-8632-bf82d9d43d8d.png)

**Comment by adi518** [comment] 2020-07-25 14:35
Then, it looks like we should start an issue with them. However this leads me to realize that every package can possibly break my tree-shake, so I think I need to find a way to seperate it away from the piece of bundle that's actually shake-able.

**Comment by mohsinulhaq** [comment] 2020-07-25 14:44
yes, they could break, it's the same with lodash, when you do
`import { isEmpty } from 'lodash';`
it is not tree-shakable, hence plugins like https://github.com/lodash/babel-plugin-lodash exist to convert the imports to
`import isEmpty from 'lodash/isEmpty'`.
You can raise an issue on their repo for understanding this. I will thumbs up your issue 😝

**Comment by adi518** [comment] 2020-07-25 14:49
We'll give it a shot.

**Comment by adi518** [comment] 2020-07-25 14:54
https://github.com/popperjs/react-popper/issues/380

**Comment by denisborovikov** [comment] 2021-01-26 17:14
We just release the hook version of the library. Could you please check if this is still an issue?

**Comment by mohsinulhaq** [comment] 2021-01-26 17:15
As per discussion with the underlying lib owner, it's an issue to be resolved from their side
as such, closing this issue. Feel free to take the issue further on the issue linked above.

**Closed by mohsinulhaq** 2021-01-26 17:15 UTC
