### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by c12mbg** [mohsinulhaq/react-popper-tooltip#42] opened 2019-01-25 14:36 UTC
Edited: Sorry, gave faulty information about the blurry text last time. Updated now, will provide codesandbox example later if i got some extra time.

The text within the tooltip is blurry in chrome when x and y is not evenly divideable by 4 in translate3d.
Examples: 

Clear text example =>  transform: translate3d(192px, 344px, 0px).
Here 192/4 = 48. and 344/4 = 86. So both x and y are being integers.

Blurry text example => transform: translate3d(6px, 30px, 0px).
Here 6/4 = 1.5. and 30/4 = 7.5. So both x and y have decimals.
It will also be blurry if either of x or y have some decimals after divided by 4.

**Comment by mohsinulhaq** [comment] 2019-01-25 16:15
Can you atleast add some code snippet of your complete usage? A codesandbox would be even better.
Thanks.

**Comment by mohsinulhaq** [comment] 2019-01-30 11:52
Closing as there is no reply from OP. Feel free to reopen.

**Comment by mohsinulhaq** [comment] 2019-01-30 11:53
ohh...i see that you edited the issue itself. You could have just replied. Reopening now.

**Comment by mohsinulhaq** [comment] 2019-02-01 06:58
i don't see blur either in mac or windows.
Which OS is this and how do u set the translate value on the tooltip?

**Comment by c12mbg** [comment] 2019-02-25 09:57
I'm on windows, but the problem only arises in Chrome webbrowser, and the text is sharp in both edge, and firefox. I'm setting the value by changing it in the DOM, in the element containing class="tooltip-container".

**Comment by mohsinulhaq** [comment] 2019-02-25 10:35
can u share a minimal codesandbox with your particular usage. That would be most helpful.

**Comment by mohsinulhaq** [comment] 2019-02-25 10:57
I tried manually setting translate3d(6px, 30px, 0px) on a tooltip in windows codesandbox, and I don't see any blurry text.

**Comment by mohsinulhaq** [comment] 2019-03-04 16:58
Hi, any codesandbox yet?

**Comment by mohsinulhaq** [comment] 2019-03-26 18:58
Closing because of no reproduction example from OP. Please feel free to re-open.

**Closed by mohsinulhaq** 2019-03-26 18:58 UTC
