### ISSUE TITLE
Upgrade to latest popper packages

### ISSUE THREAD

**Issue by ndelangen** [mohsinulhaq/react-popper-tooltip#94] opened 2020-06-11 09:55 UTC
**Is your feature request related to a problem? Please describe.**
popper.js v1 has been deprecated

**Describe the solution you'd like**
Upgrading all popper related packages

**Describe alternatives you've considered**
none

**Additional context**
https://github.com/storybookjs/storybook/issues/9961#issuecomment-642539585

**Comment by stof** [comment] 2020-06-11 09:57
@ndelangen I think this is a duplicate of #92

**Closed** 2020-06-11 10:09 UTC
