### ISSUE TITLE
When followCursor is true, the tooltip isn't respecting boundaries

### ISSUE THREAD

**Issue by kitze** [mohsinulhaq/react-popper-tooltip#46] opened 2019-02-08 10:06 UTC
I'm trying to use this library to build a context menu that's gonna show up at the exact mouse position on right click. So I'm using `trigger="right-click" followCursor={true}` and it's fine, except the popper doesn't move to the other side when it doesn't have enough space or if it's out of the scroll area.

Any ideas?

**Comment by mohsinulhaq** [comment] 2019-02-08 10:17
I am aware of this. This is because react-popper, the underlying library doesn't support followCursor, as such with that prop turned on, I myself take care of rendering the tooltip instead of react-popper (which is only capable to rendering wrt the trigger boundaries). That custom logic just renders the component at the click area, no calculations done wrt viewport/scroll-container. Pull Requests are welcome to enhance that aspect. :)
https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/TooltipTrigger.tsx#L91
This is where I override the positions sent from react-popper.

**Comment by mohsinulhaq** [comment] 2019-02-23 10:05
Hi @kitze, I have released react-popper-tooltip@2.8.1-alpha.1 with a potential fix respecting viewport boundaries with `followCursor`. Please give it a spin and let me know if anything's missing. 🙂

**Comment by mohsinulhaq** [comment] 2019-02-25 14:18
If you have moved to some other library, please let me know so that we can close this issue. Thanks.

**Comment by mohsinulhaq** [comment] 2019-03-02 18:10
Closing due to no response from OP. The issue is fixed and will be available in v2.8.1

**Closed by mohsinulhaq** 2019-03-02 18:10 UTC
