### ISSUE TITLE
interactive + tooltip offset bug

### ISSUE THREAD

**Issue by ajmerik121** [mohsinulhaq/react-popper-tooltip#114] opened 2021-02-03 08:58 UTC

**Comment by mohsinulhaq** [comment] 2021-02-04 20:17
@ajmerik121 https://codesandbox.io/s/bold-feistel-j0zxp?file=/src/index.js
I see no flickering with 0 offset and interactive `true`. Can you produce a minimal codesandbox by forking our basic example?

**Comment by ajmerik121** [comment] 2021-02-04 23:03
i think u cant understand what im saying , my english is pretty bad and i try my best to find the best words , offset : [ 0 , 20 ] ( any offset > 0) and interactive : true is not working well together ( delayHide causes another bug ) https://codesandbox.io/s/wonderful-field-d0bse

**Comment by mohsinulhaq** [comment] 2021-02-05 09:35
okay, my bad, I misread it as 0 offset, but even with > 0 offset, I get no flickering, so I am no longer sure what you mean by flickering. Also since you have used a rather large offset of 20, you would definitely need to add some reasonable delayHide if you want users to be able to move to the tooltip in order to persist it.

Here's a recording with your Codesandbox
https://user-images.githubusercontent.com/7688231/107015929-5490ee00-67c3-11eb-8b11-77293841e5a3.mov

And here's a recording with your Codesandbox with a 250ms `delayHide` (average human response time).

https://user-images.githubusercontent.com/7688231/107016052-7d18e800-67c3-11eb-9fe6-fd9c8457713c.mov

**Comment by czabaj** [comment] 2021-02-05 10:15
I just play with the code and I think I found the root cause. I might be able to prepare PR and describe it all in there.

**Comment by mohsinulhaq** [comment] 2021-02-05 10:19
@czabaj sure, feel free to do so

**Comment by czabaj** [comment] 2021-02-05 10:26
Yes, got it!

When the _tooltip overlaps the trigger_ and when you move the cursor over the overlapping section, your cursor points to the tooltip and the trigger receive `mouseleave` event and set the visibility `false`, but when the tooltip hides and your cursor is still on the overlaping section, the trigger receives `mouseenter` and sets the visibility `true`, but, as the tooltip emerges, the trigger receives `mouseleave` and so it goes ad infinitum.

The quick workaround is
* set the offset big enough so the trigger and tooltip has no overlapping section,
* usually, only the arrow overlaps, so set the `pointer-events: none` CSS rule on the tooltip-arrow,
* optionally, if your tooltip contains non-clickable content, set `poninter-events: none` rule for the whole tooltip,

To make a robust solution, we must detect `mouseenter` and `mouseleave` on the triggers bounding box, not on the element it self.

**Comment by mohsinulhaq** [comment] 2021-02-05 10:36
@czabaj what you are describing is quite different from what @ajmerik121 is talking about.

What you just described happens when interactive is false (default) and offset is set such that the arrow overlaps the trigger. This was the reason we had put the default offset as [0, 7] in our shipped CSS, which is the first solution that you have described. (I assume you are not using our CSS for styling?)

We had also considered solutions 2 and 3 before releasing but finally went with the offset method and left pointer-events to the end-user in case they want a lower offset or are not using our CSS.

**Comment by ajmerik121** [comment] 2021-02-05 11:19
Uploading bandicam 2021-02-05 13-18-17-015.mp4…

**Comment by ajmerik121** [comment] 2021-02-05 11:20
delayHide + react spring causing flickering , when mouse leave tooltip should close
https://user-images.githubusercontent.com/74120006/107027475-d9284000-67b4-11eb-8a62-2e26f2695259.mp4

**Comment by mohsinulhaq** [comment] 2021-02-05 12:54
@ajmerik121 
what did you select your delayHide value as?
Here's mine with the same config as what you talked about. I also made the tooltip a bit bigger so that, I don't mistakenly wander around for more than 250ms, and miss entering the tooltip while swinging side to side.

https://user-images.githubusercontent.com/7688231/107036066-0a1d6a80-67df-11eb-89de-be124c1c436d.mov

**Comment by mohsinulhaq** [comment] 2021-02-09 06:28
Since the OP updated the description to be empty, closing this issue as resolved. Feel free to reopen if it still persists.

**Closed by mohsinulhaq** 2021-02-09 06:28 UTC
