### ISSUE TITLE
followCursor tooltip - reposition if you mouse over tooltip

### ISSUE THREAD

**Issue by penx** [mohsinulhaq/react-popper-tooltip#89] opened 2020-03-16 17:10 UTC
**Describe the bug**
In `followCursor` mode, the tooltip doesn't reposition if you move the mouse over the tooltip

**To Reproduce**

1. Go to the follow cursor demo https://react-popper-tooltip.netlify.com/#follow-cursor
2. Mouse over to see tooltip
3. Quickly move the mouse over the tooltip
4. Tooltip doesn't reposition

**Expected behavior**
react-popper-tooltip should ensure tooltip doesn't sit underneath cursor when in followCursor mode.

**Screenshots**

![follow-cursor](https://user-images.githubusercontent.com/1027024/76782892-df7e8980-67a8-11ea-9c8d-69499601811d.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version: 83.0.4086.0

**Comment by mohsinulhaq** [comment] 2020-03-16 17:57
this is the intended behaviour, as it's tracking mouse position within the bounds of the trigger and not the tooltip or anything else

**Comment by penx** [comment] 2020-03-16 18:02
This is "within the bounds of the trigger" but the tooltip is overlayed on top of it. If the tooltip was repositioned instantly then you would never see this issue as you wouldn't be able to mouse over it. The issue happens when you quickly move the mouse over the tooltip before it has a chance to reposition.

I accept this may be hard to solve due to the inner workings of what's happening, but I'd question whether this is intended behaviour.

**Comment by penx** [comment] 2020-03-16 18:04
<img width="1004" alt="Touch Bar Shot 2020-03-09 at 17 47 56" src="https://user-images.githubusercontent.com/1027024/76787281-97636500-67b0-11ea-8afb-882d1e8af9d3.png">

**Comment by penx** [comment] 2020-03-16 18:04
![followCursor](https://user-images.githubusercontent.com/1027024/76787298-a4805400-67b0-11ea-97bf-c702721e46ba.gif)

**Comment by mohsinulhaq** [comment] 2020-03-16 18:06
oh got it, yes the positioning happens asynchronously, so your situation can occur. Right now I don't have the bandwidth to look into it. Feel free to raise a PR. Otherwise I'll give it a look this weekend.

**Comment by denisborovikov** [comment] 2020-03-16 18:13
I believe, if you add `pointer-events: none` to the `.tooltip-container` it should resolve this issue.

**Comment by penx** [comment] 2020-03-16 18:23
Yep that works for me, thanks! Happy for this issue to be closed, unless you think it needs to be solved in the lib or added to the docs.

**Comment by penx** [comment] 2020-03-16 18:39
on second thoughts, if it's easy enough to add `pointer-events: none`, but only when followCursor is true, then probably a good idea to do this in react-popper-tooltip so others don't get unexpected jankiness

**Comment by mohsinulhaq** [comment] 2020-03-17 14:01
@penx the library doesn't and shouldn't come with inherent CSS, just event handlers, CSS is kept to the user to add. Hence I'm closing the issue.

**Closed by mohsinulhaq** 2020-03-17 14:01 UTC
